# Generated by Django 4.2.7 on 2023-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerbook',
            name='photo',
            field=models.ImageField(default='none', upload_to='images'),
        ),
    ]
